apiVersion: v1
kind: Service
metadata:
  name: flclient-service
spec:
  type: NodePort
  selector:
    app: flclient-app
  ports:
    - protocol: "TCP"
      port: 3001
      targetPort: 3001
      nodePort: 30001
  # externalIPs:
  #   - 192.168.17.35
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flclient-deployment
  labels:
    app: flclient-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flclient-app
  template:
    metadata:
      name: flclient
      labels:
        app: flclient-app
    spec:
      # nodeName: nodeserf2
      containers:
        - image: lucaserf/flclient:latest
          imagePullPolicy: Always
          name: flclient
          ports:
            - containerPort: 3001
---

